j: 0 bis 5
no display found. Using non-interactive Agg backend
[5, 5, 5]
Files already downloaded and verified
count0: 487386

Epoch: [1 | 5] LR: 0.100000
Epoch: [1][0/196]	Time 0.663 (0.663)	Data 0.263 (0.263)	Loss 3.9229 (3.9229)	Acc@1 7.422 (7.422)	Acc@5 44.922 (44.922)
Epoch: [1][64/196]	Time 0.435 (0.458)	Data 0.000 (0.004)	Loss 2.7609 (3.0315)	Acc@1 32.422 (23.552)	Acc@5 83.203 (75.883)
Epoch: [1][128/196]	Time 0.450 (0.456)	Data 0.000 (0.002)	Loss 2.5697 (2.8480)	Acc@1 39.453 (28.679)	Acc@5 89.062 (81.317)
Epoch: [1][192/196]	Time 0.198 (0.417)	Data 0.000 (0.002)	Loss 2.2077 (2.7169)	Acc@1 52.344 (32.479)	Acc@5 92.578 (84.250)
Traceback (most recent call last):
  File "main.py", line 824, in <module>
    main()
  File "main.py", line 380, in main
    test_epoch_time])
  File "/home/jessica.buehler/MA_Source/src/utils/logger.py", line 71, in append
    assert len(self.names) == len(numbers), 'Numbers do not match names'
AssertionError: Numbers do not match names
j: 6 bis 10
no display found. Using non-interactive Agg backend
[5, 5, 5]
Files already downloaded and verified
==> Resuming from checkpoint..
count0: 302064

Epoch: [116 | 120] LR: 0.010000
Epoch: [116][0/196]	Time 0.907 (0.907)	Data 0.266 (0.266)	Loss 0.5196 (0.5196)	Acc@1 94.141 (94.141)	Acc@5 100.000 (100.000)
Epoch: [116][64/196]	Time 0.397 (0.397)	Data 0.000 (0.004)	Loss 0.4468 (0.4996)	Acc@1 96.094 (94.459)	Acc@5 100.000 (99.892)
Epoch: [116][128/196]	Time 0.490 (0.401)	Data 0.000 (0.002)	Loss 0.4873 (0.4990)	Acc@1 94.141 (94.292)	Acc@5 100.000 (99.882)
Epoch: [116][192/196]	Time 0.274 (0.384)	Data 0.000 (0.002)	Loss 0.5273 (0.5022)	Acc@1 94.531 (94.100)	Acc@5 99.609 (99.883)
Traceback (most recent call last):
  File "main.py", line 824, in <module>
    main()
  File "main.py", line 380, in main
    test_epoch_time])
  File "/home/jessica.buehler/MA_Source/src/utils/logger.py", line 71, in append
    assert len(self.names) == len(numbers), 'Numbers do not match names'
AssertionError: Numbers do not match names
j: 11 bis 15
no display found. Using non-interactive Agg backend
[5, 5, 5]
Files already downloaded and verified
==> Resuming from checkpoint..
count0: 302064

Epoch: [116 | 120] LR: 0.010000
Epoch: [116][0/196]	Time 1.168 (1.168)	Data 0.264 (0.264)	Loss 0.5521 (0.5521)	Acc@1 91.797 (91.797)	Acc@5 100.000 (100.000)
Epoch: [116][64/196]	Time 0.409 (0.413)	Data 0.000 (0.004)	Loss 0.4521 (0.4984)	Acc@1 95.312 (94.363)	Acc@5 100.000 (99.886)
Epoch: [116][128/196]	Time 0.398 (0.407)	Data 0.000 (0.002)	Loss 0.4486 (0.4983)	Acc@1 96.484 (94.292)	Acc@5 100.000 (99.900)
Epoch: [116][192/196]	Time 0.278 (0.395)	Data 0.000 (0.002)	Loss 0.4916 (0.5006)	Acc@1 94.922 (94.106)	Acc@5 100.000 (99.891)
Traceback (most recent call last):
  File "main.py", line 824, in <module>
    main()
  File "main.py", line 380, in main
    test_epoch_time])
  File "/home/jessica.buehler/MA_Source/src/utils/logger.py", line 71, in append
    assert len(self.names) == len(numbers), 'Numbers do not match names'
AssertionError: Numbers do not match names
j: 16 bis 20
no display found. Using non-interactive Agg backend
[5, 5, 5]
Files already downloaded and verified
==> Resuming from checkpoint..
count0: 302064

Epoch: [116 | 120] LR: 0.010000
Epoch: [116][0/196]	Time 0.884 (0.884)	Data 0.261 (0.261)	Loss 0.4770 (0.4770)	Acc@1 94.922 (94.922)	Acc@5 99.609 (99.609)
Epoch: [116][64/196]	Time 0.217 (0.230)	Data 0.000 (0.004)	Loss 0.4684 (0.4932)	Acc@1 95.312 (94.279)	Acc@5 100.000 (99.880)
Epoch: [116][128/196]	Time 0.378 (0.283)	Data 0.000 (0.002)	Loss 0.5015 (0.4979)	Acc@1 93.359 (94.125)	Acc@5 100.000 (99.876)
Epoch: [116][192/196]	Time 0.169 (0.311)	Data 0.000 (0.002)	Loss 0.5066 (0.5001)	Acc@1 94.141 (94.043)	Acc@5 100.000 (99.862)
Traceback (most recent call last):
  File "main.py", line 824, in <module>
    main()
  File "main.py", line 380, in main
    test_epoch_time])
  File "/home/jessica.buehler/MA_Source/src/utils/logger.py", line 71, in append
    assert len(self.names) == len(numbers), 'Numbers do not match names'
AssertionError: Numbers do not match names
j: 21 bis 25
no display found. Using non-interactive Agg backend
[5, 5, 5]
Files already downloaded and verified
==> Resuming from checkpoint..
count0: 302064

Epoch: [116 | 120] LR: 0.010000
Epoch: [116][0/196]	Time 1.231 (1.231)	Data 0.369 (0.369)	Loss 0.4724 (0.4724)	Acc@1 96.875 (96.875)	Acc@5 100.000 (100.000)
Epoch: [116][64/196]	Time 0.410 (0.409)	Data 0.000 (0.006)	Loss 0.4712 (0.5011)	Acc@1 94.141 (94.201)	Acc@5 100.000 (99.886)
Epoch: [116][128/196]	Time 0.401 (0.402)	Data 0.000 (0.003)	Loss 0.5248 (0.5043)	Acc@1 93.750 (94.010)	Acc@5 100.000 (99.894)
Epoch: [116][192/196]	Time 0.336 (0.397)	Data 0.000 (0.002)	Loss 0.5029 (0.5031)	Acc@1 94.141 (93.987)	Acc@5 99.609 (99.897)
Traceback (most recent call last):
  File "main.py", line 824, in <module>
    main()
  File "main.py", line 380, in main
    test_epoch_time])
  File "/home/jessica.buehler/MA_Source/src/utils/logger.py", line 71, in append
    assert len(self.names) == len(numbers), 'Numbers do not match names'
AssertionError: Numbers do not match names
j: 26 bis 30
no display found. Using non-interactive Agg backend
[5, 5, 5]
Files already downloaded and verified
==> Resuming from checkpoint..
count0: 302064

Epoch: [116 | 120] LR: 0.010000
Epoch: [116][0/196]	Time 1.015 (1.015)	Data 0.276 (0.276)	Loss 0.5295 (0.5295)	Acc@1 92.969 (92.969)	Acc@5 100.000 (100.000)
Epoch: [116][64/196]	Time 0.296 (0.398)	Data 0.000 (0.004)	Loss 0.4203 (0.5030)	Acc@1 98.047 (94.249)	Acc@5 100.000 (99.874)
Epoch: [116][128/196]	Time 0.211 (0.330)	Data 0.000 (0.002)	Loss 0.5511 (0.5038)	Acc@1 93.359 (94.071)	Acc@5 99.219 (99.870)
Epoch: [116][192/196]	Time 0.204 (0.299)	Data 0.000 (0.002)	Loss 0.5101 (0.5016)	Acc@1 94.531 (94.153)	Acc@5 99.609 (99.862)
Traceback (most recent call last):
  File "main.py", line 824, in <module>
    main()
  File "main.py", line 380, in main
    test_epoch_time])
  File "/home/jessica.buehler/MA_Source/src/utils/logger.py", line 71, in append
    assert len(self.names) == len(numbers), 'Numbers do not match names'
AssertionError: Numbers do not match names
j: 31 bis 35
no display found. Using non-interactive Agg backend
[5, 5, 5]
Files already downloaded and verified
==> Resuming from checkpoint..
count0: 302064

Epoch: [116 | 120] LR: 0.010000
Epoch: [116][0/196]	Time 0.964 (0.964)	Data 0.270 (0.270)	Loss 0.4782 (0.4782)	Acc@1 95.703 (95.703)	Acc@5 100.000 (100.000)
Epoch: [116][64/196]	Time 0.406 (0.394)	Data 0.000 (0.004)	Loss 0.4593 (0.5009)	Acc@1 95.703 (94.159)	Acc@5 100.000 (99.904)
Epoch: [116][128/196]	Time 0.405 (0.394)	Data 0.000 (0.002)	Loss 0.5951 (0.5035)	Acc@1 91.406 (94.122)	Acc@5 100.000 (99.903)
Epoch: [116][192/196]	Time 0.321 (0.390)	Data 0.000 (0.002)	Loss 0.5398 (0.5029)	Acc@1 93.359 (94.076)	Acc@5 100.000 (99.897)
Traceback (most recent call last):
  File "main.py", line 824, in <module>
    main()
  File "main.py", line 380, in main
    test_epoch_time])
  File "/home/jessica.buehler/MA_Source/src/utils/logger.py", line 71, in append
    assert len(self.names) == len(numbers), 'Numbers do not match names'
AssertionError: Numbers do not match names
j: 36 bis 40
no display found. Using non-interactive Agg backend
[5, 5, 5]
Files already downloaded and verified
==> Resuming from checkpoint..
count0: 302064

Epoch: [116 | 120] LR: 0.010000
Epoch: [116][0/196]	Time 0.983 (0.983)	Data 0.260 (0.260)	Loss 0.4630 (0.4630)	Acc@1 96.484 (96.484)	Acc@5 99.609 (99.609)
Epoch: [116][64/196]	Time 0.412 (0.378)	Data 0.000 (0.004)	Loss 0.4997 (0.4930)	Acc@1 92.969 (94.525)	Acc@5 100.000 (99.928)
Epoch: [116][128/196]	Time 0.414 (0.386)	Data 0.000 (0.002)	Loss 0.5060 (0.4999)	Acc@1 94.141 (94.180)	Acc@5 99.609 (99.906)
Epoch: [116][192/196]	Time 0.230 (0.371)	Data 0.000 (0.002)	Loss 0.4800 (0.5029)	Acc@1 94.922 (94.007)	Acc@5 100.000 (99.901)
Traceback (most recent call last):
  File "main.py", line 824, in <module>
    main()
  File "main.py", line 380, in main
    test_epoch_time])
  File "/home/jessica.buehler/MA_Source/src/utils/logger.py", line 71, in append
    assert len(self.names) == len(numbers), 'Numbers do not match names'
AssertionError: Numbers do not match names
j: 41 bis 45
no display found. Using non-interactive Agg backend
[5, 5, 5]
Files already downloaded and verified
==> Resuming from checkpoint..
count0: 302064

Epoch: [116 | 120] LR: 0.010000
Epoch: [116][0/196]	Time 0.771 (0.771)	Data 0.256 (0.256)	Loss 0.4721 (0.4721)	Acc@1 95.312 (95.312)	Acc@5 100.000 (100.000)
Epoch: [116][64/196]	Time 0.354 (0.356)	Data 0.000 (0.004)	Loss 0.4806 (0.5038)	Acc@1 95.703 (94.081)	Acc@5 99.609 (99.916)
Epoch: [116][128/196]	Time 0.422 (0.378)	Data 0.000 (0.002)	Loss 0.4599 (0.5027)	Acc@1 96.484 (94.077)	Acc@5 99.609 (99.891)
Epoch: [116][192/196]	Time 0.314 (0.373)	Data 0.000 (0.001)	Loss 0.4948 (0.5017)	Acc@1 94.531 (94.007)	Acc@5 100.000 (99.889)
Traceback (most recent call last):
  File "main.py", line 824, in <module>
    main()
  File "main.py", line 380, in main
    test_epoch_time])
  File "/home/jessica.buehler/MA_Source/src/utils/logger.py", line 71, in append
    assert len(self.names) == len(numbers), 'Numbers do not match names'
AssertionError: Numbers do not match names
j: 46 bis 50
no display found. Using non-interactive Agg backend
[5, 5, 5]
Files already downloaded and verified
==> Resuming from checkpoint..
count0: 302064

Epoch: [116 | 120] LR: 0.010000
Epoch: [116][0/196]	Time 1.015 (1.015)	Data 0.261 (0.261)	Loss 0.5911 (0.5911)	Acc@1 92.188 (92.188)	Acc@5 100.000 (100.000)
Epoch: [116][64/196]	Time 0.435 (0.368)	Data 0.000 (0.004)	Loss 0.5369 (0.5056)	Acc@1 94.141 (94.129)	Acc@5 99.609 (99.934)
Epoch: [116][128/196]	Time 0.425 (0.383)	Data 0.000 (0.002)	Loss 0.4839 (0.5017)	Acc@1 94.141 (94.086)	Acc@5 100.000 (99.918)
Epoch: [116][192/196]	Time 0.319 (0.372)	Data 0.000 (0.002)	Loss 0.5073 (0.5018)	Acc@1 93.750 (94.001)	Acc@5 99.609 (99.909)
Traceback (most recent call last):
  File "main.py", line 824, in <module>
    main()
  File "main.py", line 380, in main
    test_epoch_time])
  File "/home/jessica.buehler/MA_Source/src/utils/logger.py", line 71, in append
    assert len(self.names) == len(numbers), 'Numbers do not match names'
AssertionError: Numbers do not match names
j: 51 bis 55
no display found. Using non-interactive Agg backend
[5, 5, 5]
Files already downloaded and verified
==> Resuming from checkpoint..
count0: 302064

Epoch: [116 | 120] LR: 0.010000
Epoch: [116][0/196]	Time 0.772 (0.772)	Data 0.251 (0.251)	Loss 0.5101 (0.5101)	Acc@1 92.188 (92.188)	Acc@5 100.000 (100.000)
Epoch: [116][64/196]	Time 0.144 (0.237)	Data 0.000 (0.004)	Loss 0.4636 (0.4979)	Acc@1 94.922 (94.231)	Acc@5 100.000 (99.868)
Epoch: [116][128/196]	Time 0.300 (0.223)	Data 0.000 (0.002)	Loss 0.5217 (0.5016)	Acc@1 92.969 (94.153)	Acc@5 100.000 (99.873)
Epoch: [116][192/196]	Time 0.320 (0.243)	Data 0.000 (0.001)	Loss 0.4739 (0.5026)	Acc@1 93.750 (94.058)	Acc@5 100.000 (99.870)
Traceback (most recent call last):
  File "main.py", line 824, in <module>
    main()
  File "main.py", line 380, in main
    test_epoch_time])
  File "/home/jessica.buehler/MA_Source/src/utils/logger.py", line 71, in append
    assert len(self.names) == len(numbers), 'Numbers do not match names'
AssertionError: Numbers do not match names
j: 56 bis 60
no display found. Using non-interactive Agg backend
[5, 5, 5]
Files already downloaded and verified
==> Resuming from checkpoint..
count0: 302064

Epoch: [116 | 120] LR: 0.010000
Epoch: [116][0/196]	Time 1.108 (1.108)	Data 0.228 (0.228)	Loss 0.5085 (0.5085)	Acc@1 94.141 (94.141)	Acc@5 100.000 (100.000)
Epoch: [116][64/196]	Time 0.333 (0.383)	Data 0.000 (0.004)	Loss 0.4999 (0.4945)	Acc@1 94.531 (94.471)	Acc@5 100.000 (99.898)
Epoch: [116][128/196]	Time 0.410 (0.363)	Data 0.000 (0.002)	Loss 0.4896 (0.4972)	Acc@1 94.141 (94.253)	Acc@5 99.609 (99.909)
Epoch: [116][192/196]	Time 0.337 (0.359)	Data 0.000 (0.001)	Loss 0.5465 (0.5030)	Acc@1 91.797 (93.960)	Acc@5 100.000 (99.893)
Traceback (most recent call last):
  File "main.py", line 824, in <module>
    main()
  File "main.py", line 380, in main
    test_epoch_time])
  File "/home/jessica.buehler/MA_Source/src/utils/logger.py", line 71, in append
    assert len(self.names) == len(numbers), 'Numbers do not match names'
AssertionError: Numbers do not match names
j: 61 bis 65
no display found. Using non-interactive Agg backend
[5, 5, 5]
Files already downloaded and verified
==> Resuming from checkpoint..
count0: 302064

Epoch: [116 | 120] LR: 0.010000
Epoch: [116][0/196]	Time 1.091 (1.091)	Data 0.272 (0.272)	Loss 0.5105 (0.5105)	Acc@1 94.141 (94.141)	Acc@5 100.000 (100.000)
Epoch: [116][64/196]	Time 0.351 (0.398)	Data 0.000 (0.004)	Loss 0.5144 (0.5024)	Acc@1 93.359 (94.303)	Acc@5 100.000 (99.922)
Epoch: [116][128/196]	Time 0.325 (0.365)	Data 0.000 (0.002)	Loss 0.5462 (0.5035)	Acc@1 91.406 (94.059)	Acc@5 100.000 (99.900)
Epoch: [116][192/196]	Time 0.213 (0.345)	Data 0.000 (0.002)	Loss 0.4430 (0.5025)	Acc@1 96.484 (94.017)	Acc@5 100.000 (99.899)
Traceback (most recent call last):
  File "main.py", line 824, in <module>
    main()
  File "main.py", line 380, in main
    test_epoch_time])
  File "/home/jessica.buehler/MA_Source/src/utils/logger.py", line 71, in append
    assert len(self.names) == len(numbers), 'Numbers do not match names'
AssertionError: Numbers do not match names
j: 66 bis 70
no display found. Using non-interactive Agg backend
[5, 5, 5]
Files already downloaded and verified
==> Resuming from checkpoint..
count0: 302064

Epoch: [116 | 120] LR: 0.010000
Epoch: [116][0/196]	Time 0.759 (0.759)	Data 0.303 (0.303)	Loss 0.5055 (0.5055)	Acc@1 94.531 (94.531)	Acc@5 100.000 (100.000)
Epoch: [116][64/196]	Time 0.334 (0.312)	Data 0.000 (0.005)	Loss 0.4725 (0.5068)	Acc@1 96.484 (93.930)	Acc@5 100.000 (99.892)
Epoch: [116][128/196]	Time 0.344 (0.349)	Data 0.000 (0.003)	Loss 0.4903 (0.5034)	Acc@1 93.750 (94.032)	Acc@5 100.000 (99.894)
Epoch: [116][192/196]	Time 0.326 (0.340)	Data 0.000 (0.002)	Loss 0.4771 (0.5023)	Acc@1 95.703 (94.066)	Acc@5 100.000 (99.883)
Traceback (most recent call last):
  File "main.py", line 824, in <module>
    main()
  File "main.py", line 380, in main
    test_epoch_time])
  File "/home/jessica.buehler/MA_Source/src/utils/logger.py", line 71, in append
    assert len(self.names) == len(numbers), 'Numbers do not match names'
AssertionError: Numbers do not match names
j: 71 bis 75
no display found. Using non-interactive Agg backend
[5, 5, 5]
Files already downloaded and verified
==> Resuming from checkpoint..
count0: 302064

Epoch: [116 | 120] LR: 0.010000
Epoch: [116][0/196]	Time 1.131 (1.131)	Data 0.289 (0.289)	Loss 0.5375 (0.5375)	Acc@1 93.359 (93.359)	Acc@5 99.219 (99.219)
Epoch: [116][64/196]	Time 0.342 (0.355)	Data 0.000 (0.005)	Loss 0.6638 (0.5056)	Acc@1 88.281 (93.924)	Acc@5 99.219 (99.862)
Epoch: [116][128/196]	Time 0.336 (0.359)	Data 0.000 (0.002)	Loss 0.5263 (0.5048)	Acc@1 93.359 (93.956)	Acc@5 100.000 (99.882)
Epoch: [116][192/196]	Time 0.336 (0.348)	Data 0.000 (0.002)	Loss 0.4998 (0.5037)	Acc@1 93.359 (93.918)	Acc@5 100.000 (99.877)
Traceback (most recent call last):
  File "main.py", line 824, in <module>
    main()
  File "main.py", line 380, in main
    test_epoch_time])
  File "/home/jessica.buehler/MA_Source/src/utils/logger.py", line 71, in append
    assert len(self.names) == len(numbers), 'Numbers do not match names'
AssertionError: Numbers do not match names
j: 76 bis 80
no display found. Using non-interactive Agg backend
[5, 5, 5]
Files already downloaded and verified
==> Resuming from checkpoint..
count0: 302064

Epoch: [116 | 120] LR: 0.010000
Epoch: [116][0/196]	Time 1.083 (1.083)	Data 0.272 (0.272)	Loss 0.4456 (0.4456)	Acc@1 96.094 (96.094)	Acc@5 100.000 (100.000)
Epoch: [116][64/196]	Time 0.247 (0.320)	Data 0.000 (0.004)	Loss 0.4853 (0.5001)	Acc@1 94.922 (94.243)	Acc@5 100.000 (99.904)
Epoch: [116][128/196]	Time 0.142 (0.246)	Data 0.000 (0.002)	Loss 0.4685 (0.5018)	Acc@1 94.922 (94.183)	Acc@5 100.000 (99.894)
Epoch: [116][192/196]	Time 0.156 (0.206)	Data 0.000 (0.002)	Loss 0.5136 (0.5007)	Acc@1 94.141 (94.187)	Acc@5 100.000 (99.903)
Traceback (most recent call last):
  File "main.py", line 824, in <module>
    main()
  File "main.py", line 380, in main
    test_epoch_time])
  File "/home/jessica.buehler/MA_Source/src/utils/logger.py", line 71, in append
    assert len(self.names) == len(numbers), 'Numbers do not match names'
AssertionError: Numbers do not match names
j: 81 bis 85
no display found. Using non-interactive Agg backend
[5, 5, 5]
Files already downloaded and verified
==> Resuming from checkpoint..
count0: 302064

Epoch: [116 | 120] LR: 0.010000
Epoch: [116][0/196]	Time 1.115 (1.115)	Data 0.275 (0.275)	Loss 0.5210 (0.5210)	Acc@1 93.750 (93.750)	Acc@5 100.000 (100.000)
Epoch: [116][64/196]	Time 0.369 (0.404)	Data 0.000 (0.004)	Loss 0.4939 (0.4954)	Acc@1 95.312 (94.381)	Acc@5 100.000 (99.898)
Epoch: [116][128/196]	Time 0.338 (0.387)	Data 0.000 (0.002)	Loss 0.5115 (0.4988)	Acc@1 93.750 (94.165)	Acc@5 100.000 (99.909)
Epoch: [116][192/196]	Time 0.253 (0.364)	Data 0.000 (0.002)	Loss 0.5466 (0.5006)	Acc@1 91.016 (94.068)	Acc@5 100.000 (99.901)
Traceback (most recent call last):
  File "main.py", line 824, in <module>
    main()
  File "main.py", line 380, in main
    test_epoch_time])
  File "/home/jessica.buehler/MA_Source/src/utils/logger.py", line 71, in append
    assert len(self.names) == len(numbers), 'Numbers do not match names'
AssertionError: Numbers do not match names
j: 86 bis 90
no display found. Using non-interactive Agg backend
[5, 5, 5]
Files already downloaded and verified
==> Resuming from checkpoint..
count0: 302064

Epoch: [116 | 120] LR: 0.010000
Epoch: [116][0/196]	Time 1.101 (1.101)	Data 0.245 (0.245)	Loss 0.4863 (0.4863)	Acc@1 95.312 (95.312)	Acc@5 100.000 (100.000)
Epoch: [116][64/196]	Time 0.382 (0.405)	Data 0.000 (0.004)	Loss 0.5318 (0.5022)	Acc@1 93.359 (94.411)	Acc@5 100.000 (99.886)
Epoch: [116][128/196]	Time 0.322 (0.397)	Data 0.000 (0.002)	Loss 0.4633 (0.5014)	Acc@1 96.094 (94.298)	Acc@5 100.000 (99.879)
Epoch: [116][192/196]	Time 0.263 (0.366)	Data 0.000 (0.001)	Loss 0.5282 (0.5019)	Acc@1 92.188 (94.175)	Acc@5 100.000 (99.891)
Traceback (most recent call last):
  File "main.py", line 824, in <module>
    main()
  File "main.py", line 380, in main
    test_epoch_time])
  File "/home/jessica.buehler/MA_Source/src/utils/logger.py", line 71, in append
    assert len(self.names) == len(numbers), 'Numbers do not match names'
AssertionError: Numbers do not match names
j: 91 bis 95
no display found. Using non-interactive Agg backend
[5, 5, 5]
Files already downloaded and verified
==> Resuming from checkpoint..
count0: 302064

Epoch: [116 | 120] LR: 0.010000
Epoch: [116][0/196]	Time 0.888 (0.888)	Data 0.265 (0.265)	Loss 0.4855 (0.4855)	Acc@1 94.141 (94.141)	Acc@5 100.000 (100.000)
Epoch: [116][64/196]	Time 0.335 (0.327)	Data 0.000 (0.004)	Loss 0.5215 (0.5049)	Acc@1 92.578 (94.081)	Acc@5 100.000 (99.880)
Epoch: [116][128/196]	Time 0.353 (0.326)	Data 0.000 (0.002)	Loss 0.4861 (0.5056)	Acc@1 96.094 (94.098)	Acc@5 99.609 (99.876)
Epoch: [116][192/196]	Time 0.321 (0.334)	Data 0.000 (0.002)	Loss 0.4546 (0.5027)	Acc@1 95.312 (94.112)	Acc@5 100.000 (99.877)
Traceback (most recent call last):
  File "main.py", line 824, in <module>
    main()
  File "main.py", line 380, in main
    test_epoch_time])
  File "/home/jessica.buehler/MA_Source/src/utils/logger.py", line 71, in append
    assert len(self.names) == len(numbers), 'Numbers do not match names'
AssertionError: Numbers do not match names
j: 96 bis 100
no display found. Using non-interactive Agg backend
[5, 5, 5]
Files already downloaded and verified
==> Resuming from checkpoint..
count0: 302064

Epoch: [116 | 120] LR: 0.010000
Epoch: [116][0/196]	Time 1.109 (1.109)	Data 0.282 (0.282)	Loss 0.5511 (0.5511)	Acc@1 92.578 (92.578)	Acc@5 100.000 (100.000)
Epoch: [116][64/196]	Time 0.403 (0.404)	Data 0.000 (0.005)	Loss 0.5037 (0.5035)	Acc@1 94.531 (94.093)	Acc@5 99.609 (99.892)
Epoch: [116][128/196]	Time 0.350 (0.369)	Data 0.000 (0.002)	Loss 0.4341 (0.5025)	Acc@1 96.094 (94.013)	Acc@5 100.000 (99.885)
Epoch: [116][192/196]	Time 0.325 (0.355)	Data 0.000 (0.002)	Loss 0.4861 (0.5022)	Acc@1 94.531 (93.985)	Acc@5 100.000 (99.885)
Traceback (most recent call last):
  File "main.py", line 824, in <module>
    main()
  File "main.py", line 380, in main
    test_epoch_time])
  File "/home/jessica.buehler/MA_Source/src/utils/logger.py", line 71, in append
    assert len(self.names) == len(numbers), 'Numbers do not match names'
AssertionError: Numbers do not match names
j: 101 bis 105
no display found. Using non-interactive Agg backend
[5, 5, 5]
Files already downloaded and verified
==> Resuming from checkpoint..
count0: 302064

Epoch: [116 | 120] LR: 0.010000
Epoch: [116][0/196]	Time 1.112 (1.112)	Data 0.253 (0.253)	Loss 0.5108 (0.5108)	Acc@1 94.922 (94.922)	Acc@5 99.609 (99.609)
Epoch: [116][64/196]	Time 0.304 (0.388)	Data 0.000 (0.004)	Loss 0.5634 (0.5011)	Acc@1 91.797 (94.111)	Acc@5 100.000 (99.928)
Epoch: [116][128/196]	Time 0.140 (0.307)	Data 0.000 (0.002)	Loss 0.5684 (0.5046)	Acc@1 90.625 (93.907)	Acc@5 100.000 (99.915)
Epoch: [116][192/196]	Time 0.125 (0.242)	Data 0.000 (0.002)	Loss 0.5382 (0.5029)	Acc@1 92.188 (93.948)	Acc@5 100.000 (99.907)
Traceback (most recent call last):
  File "main.py", line 824, in <module>
    main()
  File "main.py", line 380, in main
    test_epoch_time])
  File "/home/jessica.buehler/MA_Source/src/utils/logger.py", line 71, in append
    assert len(self.names) == len(numbers), 'Numbers do not match names'
AssertionError: Numbers do not match names
j: 106 bis 110
no display found. Using non-interactive Agg backend
[5, 5, 5]
Files already downloaded and verified
==> Resuming from checkpoint..
count0: 302064

Epoch: [116 | 120] LR: 0.010000
Epoch: [116][0/196]	Time 1.086 (1.086)	Data 0.265 (0.265)	Loss 0.5577 (0.5577)	Acc@1 92.578 (92.578)	Acc@5 100.000 (100.000)
Epoch: [116][64/196]	Time 0.398 (0.404)	Data 0.000 (0.004)	Loss 0.5145 (0.5039)	Acc@1 93.750 (94.207)	Acc@5 100.000 (99.886)
Epoch: [116][128/196]	Time 0.397 (0.397)	Data 0.000 (0.002)	Loss 0.4698 (0.5052)	Acc@1 95.703 (94.113)	Acc@5 100.000 (99.876)
Epoch: [116][192/196]	Time 0.259 (0.384)	Data 0.000 (0.002)	Loss 0.4986 (0.5036)	Acc@1 94.141 (94.001)	Acc@5 100.000 (99.881)
Traceback (most recent call last):
  File "main.py", line 824, in <module>
    main()
  File "main.py", line 380, in main
    test_epoch_time])
  File "/home/jessica.buehler/MA_Source/src/utils/logger.py", line 71, in append
    assert len(self.names) == len(numbers), 'Numbers do not match names'
AssertionError: Numbers do not match names
j: 111 bis 115
no display found. Using non-interactive Agg backend
[5, 5, 5]
Files already downloaded and verified
==> Resuming from checkpoint..
count0: 302064

Epoch: [116 | 120] LR: 0.010000
Epoch: [116][0/196]	Time 1.115 (1.115)	Data 0.243 (0.243)	Loss 0.5535 (0.5535)	Acc@1 92.969 (92.969)	Acc@5 100.000 (100.000)
Epoch: [116][64/196]	Time 0.383 (0.404)	Data 0.000 (0.004)	Loss 0.5716 (0.5025)	Acc@1 90.625 (94.093)	Acc@5 99.609 (99.880)
Epoch: [116][128/196]	Time 0.412 (0.400)	Data 0.000 (0.002)	Loss 0.4850 (0.5020)	Acc@1 94.141 (94.062)	Acc@5 99.609 (99.891)
Epoch: [116][192/196]	Time 0.160 (0.376)	Data 0.000 (0.001)	Loss 0.5037 (0.5029)	Acc@1 94.141 (94.023)	Acc@5 100.000 (99.885)
Traceback (most recent call last):
  File "main.py", line 824, in <module>
    main()
  File "main.py", line 380, in main
    test_epoch_time])
  File "/home/jessica.buehler/MA_Source/src/utils/logger.py", line 71, in append
    assert len(self.names) == len(numbers), 'Numbers do not match names'
AssertionError: Numbers do not match names
j: 116 bis 120
no display found. Using non-interactive Agg backend
[5, 5, 5]
Files already downloaded and verified
==> Resuming from checkpoint..
count0: 302064

Epoch: [116 | 120] LR: 0.010000
Epoch: [116][0/196]	Time 0.860 (0.860)	Data 0.278 (0.278)	Loss 0.4804 (0.4804)	Acc@1 94.922 (94.922)	Acc@5 100.000 (100.000)
Epoch: [116][64/196]	Time 0.414 (0.367)	Data 0.000 (0.004)	Loss 0.5221 (0.4999)	Acc@1 93.359 (94.219)	Acc@5 99.219 (99.826)
Epoch: [116][128/196]	Time 0.404 (0.380)	Data 0.000 (0.002)	Loss 0.5292 (0.5045)	Acc@1 90.625 (94.020)	Acc@5 100.000 (99.867)
Epoch: [116][192/196]	Time 0.315 (0.384)	Data 0.000 (0.002)	Loss 0.4563 (0.5027)	Acc@1 96.094 (94.066)	Acc@5 100.000 (99.879)
Traceback (most recent call last):
  File "main.py", line 824, in <module>
    main()
  File "main.py", line 380, in main
    test_epoch_time])
  File "/home/jessica.buehler/MA_Source/src/utils/logger.py", line 71, in append
    assert len(self.names) == len(numbers), 'Numbers do not match names'
AssertionError: Numbers do not match names
j: 121 bis 125
no display found. Using non-interactive Agg backend
[5, 5, 5]
Files already downloaded and verified
==> Resuming from checkpoint..
count0: 302064

Epoch: [116 | 120] LR: 0.010000
Epoch: [116][0/196]	Time 1.241 (1.241)	Data 0.359 (0.359)	Loss 0.4700 (0.4700)	Acc@1 94.531 (94.531)	Acc@5 100.000 (100.000)
Epoch: [116][64/196]	Time 0.384 (0.408)	Data 0.000 (0.006)	Loss 0.4707 (0.5041)	Acc@1 96.875 (94.177)	Acc@5 100.000 (99.898)
Epoch: [116][128/196]	Time 0.375 (0.399)	Data 0.000 (0.003)	Loss 0.4830 (0.5025)	Acc@1 93.359 (94.177)	Acc@5 100.000 (99.885)
Epoch: [116][192/196]	Time 0.331 (0.395)	Data 0.000 (0.002)	Loss 0.4634 (0.5019)	Acc@1 95.312 (94.076)	Acc@5 100.000 (99.872)
Traceback (most recent call last):
  File "main.py", line 824, in <module>
    main()
  File "main.py", line 380, in main
    test_epoch_time])
  File "/home/jessica.buehler/MA_Source/src/utils/logger.py", line 71, in append
    assert len(self.names) == len(numbers), 'Numbers do not match names'
AssertionError: Numbers do not match names
j: 126 bis 130
no display found. Using non-interactive Agg backend
[5, 5, 5]
Files already downloaded and verified
==> Resuming from checkpoint..
count0: 302064

Epoch: [116 | 120] LR: 0.010000
Epoch: [116][0/196]	Time 0.560 (0.560)	Data 0.227 (0.227)	Loss 0.4664 (0.4664)	Acc@1 94.141 (94.141)	Acc@5 100.000 (100.000)
Epoch: [116][64/196]	Time 0.309 (0.241)	Data 0.000 (0.004)	Loss 0.4721 (0.4956)	Acc@1 92.969 (94.345)	Acc@5 100.000 (99.886)
Epoch: [116][128/196]	Time 0.389 (0.309)	Data 0.000 (0.002)	Loss 0.4927 (0.4997)	Acc@1 93.359 (94.107)	Acc@5 99.609 (99.873)
Epoch: [116][192/196]	Time 0.357 (0.319)	Data 0.000 (0.001)	Loss 0.4887 (0.5013)	Acc@1 92.188 (94.031)	Acc@5 100.000 (99.885)
Traceback (most recent call last):
  File "main.py", line 824, in <module>
    main()
  File "main.py", line 380, in main
    test_epoch_time])
  File "/home/jessica.buehler/MA_Source/src/utils/logger.py", line 71, in append
    assert len(self.names) == len(numbers), 'Numbers do not match names'
AssertionError: Numbers do not match names
j: 131 bis 135
no display found. Using non-interactive Agg backend
[5, 5, 5]
Files already downloaded and verified
==> Resuming from checkpoint..
count0: 302064

Epoch: [116 | 120] LR: 0.010000
Epoch: [116][0/196]	Time 0.987 (0.987)	Data 0.265 (0.265)	Loss 0.4800 (0.4800)	Acc@1 95.312 (95.312)	Acc@5 100.000 (100.000)
Epoch: [116][64/196]	Time 0.428 (0.354)	Data 0.000 (0.004)	Loss 0.5316 (0.4991)	Acc@1 91.797 (94.297)	Acc@5 100.000 (99.886)
Epoch: [116][128/196]	Time 0.403 (0.373)	Data 0.000 (0.002)	Loss 0.5331 (0.5028)	Acc@1 93.359 (94.050)	Acc@5 99.609 (99.888)
Epoch: [116][192/196]	Time 0.340 (0.359)	Data 0.000 (0.002)	Loss 0.4966 (0.5019)	Acc@1 94.922 (94.074)	Acc@5 100.000 (99.885)
Traceback (most recent call last):
  File "main.py", line 824, in <module>
    main()
  File "main.py", line 380, in main
    test_epoch_time])
  File "/home/jessica.buehler/MA_Source/src/utils/logger.py", line 71, in append
    assert len(self.names) == len(numbers), 'Numbers do not match names'
AssertionError: Numbers do not match names
j: 136 bis 140
no display found. Using non-interactive Agg backend
[5, 5, 5]
Files already downloaded and verified
==> Resuming from checkpoint..
count0: 302064

Epoch: [116 | 120] LR: 0.010000
Epoch: [116][0/196]	Time 0.921 (0.921)	Data 0.264 (0.264)	Loss 0.5565 (0.5565)	Acc@1 92.188 (92.188)	Acc@5 99.609 (99.609)
Epoch: [116][64/196]	Time 0.358 (0.339)	Data 0.000 (0.004)	Loss 0.5080 (0.5030)	Acc@1 93.750 (94.207)	Acc@5 100.000 (99.910)
Epoch: [116][128/196]	Time 0.209 (0.329)	Data 0.000 (0.002)	Loss 0.5660 (0.5040)	Acc@1 91.406 (94.059)	Acc@5 100.000 (99.915)
Epoch: [116][192/196]	Time 0.156 (0.274)	Data 0.000 (0.002)	Loss 0.4935 (0.5035)	Acc@1 93.750 (94.003)	Acc@5 100.000 (99.901)
Traceback (most recent call last):
  File "main.py", line 824, in <module>
    main()
  File "main.py", line 380, in main
    test_epoch_time])
  File "/home/jessica.buehler/MA_Source/src/utils/logger.py", line 71, in append
    assert len(self.names) == len(numbers), 'Numbers do not match names'
AssertionError: Numbers do not match names
j: 141 bis 145
no display found. Using non-interactive Agg backend
[5, 5, 5]
Files already downloaded and verified
==> Resuming from checkpoint..
count0: 302064

Epoch: [116 | 120] LR: 0.010000
Epoch: [116][0/196]	Time 0.850 (0.850)	Data 0.239 (0.239)	Loss 0.5062 (0.5062)	Acc@1 94.141 (94.141)	Acc@5 100.000 (100.000)
Epoch: [116][64/196]	Time 0.399 (0.361)	Data 0.000 (0.004)	Loss 0.5087 (0.5029)	Acc@1 95.312 (94.093)	Acc@5 99.609 (99.868)
Epoch: [116][128/196]	Time 0.504 (0.377)	Data 0.000 (0.002)	Loss 0.5237 (0.5028)	Acc@1 93.359 (94.092)	Acc@5 100.000 (99.885)
Epoch: [116][192/196]	Time 0.323 (0.372)	Data 0.000 (0.001)	Loss 0.4746 (0.5056)	Acc@1 95.312 (93.944)	Acc@5 100.000 (99.864)
Traceback (most recent call last):
  File "main.py", line 824, in <module>
    main()
  File "main.py", line 380, in main
    test_epoch_time])
  File "/home/jessica.buehler/MA_Source/src/utils/logger.py", line 71, in append
    assert len(self.names) == len(numbers), 'Numbers do not match names'
AssertionError: Numbers do not match names
j: 146 bis 150
no display found. Using non-interactive Agg backend
[5, 5, 5]
Files already downloaded and verified
==> Resuming from checkpoint..
count0: 302064

Epoch: [116 | 120] LR: 0.010000
Epoch: [116][0/196]	Time 0.984 (0.984)	Data 0.259 (0.259)	Loss 0.4572 (0.4572)	Acc@1 96.875 (96.875)	Acc@5 100.000 (100.000)
Epoch: [116][64/196]	Time 0.389 (0.341)	Data 0.000 (0.004)	Loss 0.4868 (0.4976)	Acc@1 94.531 (94.477)	Acc@5 100.000 (99.874)
Epoch: [116][128/196]	Time 0.379 (0.366)	Data 0.000 (0.002)	Loss 0.4772 (0.5008)	Acc@1 95.312 (94.144)	Acc@5 100.000 (99.876)
Epoch: [116][192/196]	Time 0.292 (0.362)	Data 0.000 (0.002)	Loss 0.5081 (0.5025)	Acc@1 94.531 (93.973)	Acc@5 99.609 (99.872)
Traceback (most recent call last):
  File "main.py", line 824, in <module>
    main()
  File "main.py", line 380, in main
    test_epoch_time])
  File "/home/jessica.buehler/MA_Source/src/utils/logger.py", line 71, in append
    assert len(self.names) == len(numbers), 'Numbers do not match names'
AssertionError: Numbers do not match names
j: 151 bis 155
no display found. Using non-interactive Agg backend
[5, 5, 5]
Files already downloaded and verified
==> Resuming from checkpoint..
count0: 302064

Epoch: [116 | 120] LR: 0.010000
Epoch: [116][0/196]	Time 0.547 (0.547)	Data 0.231 (0.231)	Loss 0.5600 (0.5600)	Acc@1 91.406 (91.406)	Acc@5 99.609 (99.609)
Epoch: [116][64/196]	Time 0.239 (0.203)	Data 0.000 (0.004)	Loss 0.5079 (0.5052)	Acc@1 93.359 (93.978)	Acc@5 100.000 (99.880)
Epoch: [116][128/196]	Time 0.309 (0.252)	Data 0.000 (0.002)	Loss 0.5288 (0.5023)	Acc@1 92.969 (94.071)	Acc@5 100.000 (99.879)
Epoch: [116][192/196]	Time 0.385 (0.280)	Data 0.000 (0.001)	Loss 0.5166 (0.5001)	Acc@1 92.969 (94.080)	Acc@5 100.000 (99.875)
Traceback (most recent call last):
  File "main.py", line 824, in <module>
    main()
  File "main.py", line 380, in main
    test_epoch_time])
  File "/home/jessica.buehler/MA_Source/src/utils/logger.py", line 71, in append
    assert len(self.names) == len(numbers), 'Numbers do not match names'
AssertionError: Numbers do not match names
j: 156 bis 160
no display found. Using non-interactive Agg backend
[5, 5, 5]
Files already downloaded and verified
==> Resuming from checkpoint..
count0: 302064

Epoch: [116 | 120] LR: 0.010000
Epoch: [116][0/196]	Time 1.087 (1.087)	Data 0.369 (0.369)	Loss 0.4517 (0.4517)	Acc@1 96.094 (96.094)	Acc@5 100.000 (100.000)
Epoch: [116][64/196]	Time 0.263 (0.375)	Data 0.000 (0.006)	Loss 0.5089 (0.4980)	Acc@1 93.359 (94.465)	Acc@5 100.000 (99.856)
Epoch: [116][128/196]	Time 0.340 (0.349)	Data 0.000 (0.003)	Loss 0.5022 (0.5023)	Acc@1 94.922 (94.138)	Acc@5 100.000 (99.873)
Epoch: [116][192/196]	Time 0.307 (0.344)	Data 0.000 (0.002)	Loss 0.4931 (0.5032)	Acc@1 93.359 (93.938)	Acc@5 100.000 (99.868)
Traceback (most recent call last):
  File "main.py", line 824, in <module>
    main()
  File "main.py", line 380, in main
    test_epoch_time])
  File "/home/jessica.buehler/MA_Source/src/utils/logger.py", line 71, in append
    assert len(self.names) == len(numbers), 'Numbers do not match names'
AssertionError: Numbers do not match names
j: 161 bis 165
no display found. Using non-interactive Agg backend
[5, 5, 5]
Files already downloaded and verified
==> Resuming from checkpoint..
count0: 302064

Epoch: [116 | 120] LR: 0.010000
Epoch: [116][0/196]	Time 1.105 (1.105)	Data 0.280 (0.280)	Loss 0.5252 (0.5252)	Acc@1 94.141 (94.141)	Acc@5 99.609 (99.609)
Epoch: [116][64/196]	Time 0.304 (0.405)	Data 0.000 (0.004)	Loss 0.4875 (0.4975)	Acc@1 95.703 (94.309)	Acc@5 100.000 (99.898)
Epoch: [116][128/196]	Time 0.174 (0.332)	Data 0.000 (0.002)	Loss 0.5366 (0.5042)	Acc@1 92.578 (94.119)	Acc@5 100.000 (99.867)
Epoch: [116][192/196]	Time 0.150 (0.271)	Data 0.000 (0.002)	Loss 0.5806 (0.5035)	Acc@1 89.844 (94.058)	Acc@5 100.000 (99.860)
Traceback (most recent call last):
  File "main.py", line 824, in <module>
    main()
  File "main.py", line 380, in main
    test_epoch_time])
  File "/home/jessica.buehler/MA_Source/src/utils/logger.py", line 71, in append
    assert len(self.names) == len(numbers), 'Numbers do not match names'
AssertionError: Numbers do not match names
j: 166 bis 170
no display found. Using non-interactive Agg backend
[5, 5, 5]
Files already downloaded and verified
==> Resuming from checkpoint..
count0: 302064

Epoch: [116 | 120] LR: 0.010000
Epoch: [116][0/196]	Time 1.109 (1.109)	Data 0.290 (0.290)	Loss 0.4340 (0.4340)	Acc@1 97.656 (97.656)	Acc@5 100.000 (100.000)
Epoch: [116][64/196]	Time 0.349 (0.372)	Data 0.000 (0.005)	Loss 0.4881 (0.5007)	Acc@1 94.141 (94.405)	Acc@5 100.000 (99.892)
Epoch: [116][128/196]	Time 0.393 (0.358)	Data 0.000 (0.002)	Loss 0.5088 (0.5013)	Acc@1 94.141 (94.304)	Acc@5 100.000 (99.903)
Epoch: [116][192/196]	Time 0.341 (0.352)	Data 0.000 (0.002)	Loss 0.5035 (0.5004)	Acc@1 93.750 (94.191)	Acc@5 100.000 (99.907)
Traceback (most recent call last):
  File "main.py", line 824, in <module>
    main()
  File "main.py", line 380, in main
    test_epoch_time])
  File "/home/jessica.buehler/MA_Source/src/utils/logger.py", line 71, in append
    assert len(self.names) == len(numbers), 'Numbers do not match names'
AssertionError: Numbers do not match names
j: 171 bis 175
no display found. Using non-interactive Agg backend
[5, 5, 5]
Files already downloaded and verified
==> Resuming from checkpoint..
count0: 302064

Epoch: [116 | 120] LR: 0.010000
Epoch: [116][0/196]	Time 1.124 (1.124)	Data 0.241 (0.241)	Loss 0.4802 (0.4802)	Acc@1 94.531 (94.531)	Acc@5 100.000 (100.000)
Epoch: [116][64/196]	Time 0.335 (0.397)	Data 0.000 (0.004)	Loss 0.5676 (0.5036)	Acc@1 91.016 (94.050)	Acc@5 100.000 (99.898)
Epoch: [116][128/196]	Time 0.360 (0.362)	Data 0.000 (0.002)	Loss 0.4719 (0.5034)	Acc@1 95.703 (93.983)	Acc@5 100.000 (99.891)
Epoch: [116][192/196]	Time 0.328 (0.352)	Data 0.000 (0.001)	Loss 0.5001 (0.5028)	Acc@1 94.141 (94.001)	Acc@5 100.000 (99.877)
Traceback (most recent call last):
  File "main.py", line 824, in <module>
    main()
  File "main.py", line 380, in main
    test_epoch_time])
  File "/home/jessica.buehler/MA_Source/src/utils/logger.py", line 71, in append
    assert len(self.names) == len(numbers), 'Numbers do not match names'
AssertionError: Numbers do not match names
j: 176 bis 180
no display found. Using non-interactive Agg backend
[5, 5, 5]
Files already downloaded and verified
==> Resuming from checkpoint..
count0: 302064

Epoch: [116 | 120] LR: 0.010000
Epoch: [116][0/196]	Time 0.890 (0.890)	Data 0.287 (0.287)	Loss 0.5069 (0.5069)	Acc@1 94.531 (94.531)	Acc@5 100.000 (100.000)
Epoch: [116][64/196]	Time 0.238 (0.277)	Data 0.000 (0.005)	Loss 0.4624 (0.4986)	Acc@1 94.922 (94.279)	Acc@5 100.000 (99.880)
Epoch: [116][128/196]	Time 0.232 (0.252)	Data 0.000 (0.002)	Loss 0.5693 (0.5004)	Acc@1 91.406 (94.147)	Acc@5 100.000 (99.876)
Epoch: [116][192/196]	Time 0.411 (0.245)	Data 0.000 (0.002)	Loss 0.5155 (0.5008)	Acc@1 92.578 (94.094)	Acc@5 100.000 (99.872)
Traceback (most recent call last):
  File "main.py", line 824, in <module>
    main()
  File "main.py", line 380, in main
    test_epoch_time])
  File "/home/jessica.buehler/MA_Source/src/utils/logger.py", line 71, in append
    assert len(self.names) == len(numbers), 'Numbers do not match names'
AssertionError: Numbers do not match names
